### ISSUE TITLE
Trusted Certs are not being trusted for ScanCentral Workers

### ISSUE THREAD

**Issue by dgarozzo** [fortify/helm3-charts#26]
I am having trouble getting the ScanCentral workers to communicate with our ScanCentral Controller. The problem is certainly the fact that the /app/sca/jre/lib/security/cacerts file is not being updated to trust our trusted certs that we are passing in. Am I doing something wrong? Trying to get this working on version 22.1 so we can replace our existing 22.1 workers.

**Comment by brandon-langley-mf** [comment]
Hi, thanks for raising this issue, and sorry for the delay in getting back to you. We’ve been transitioning the Fortify Helm charts to Docker Hub, and the older Helm charts that used to be hosted in this repository have now been deprecated. If you think this issue is still relevant for the new Helm charts hosted on Docker Hub, please raise a support ticket through the regular OpenText support channels. We will no longer be monitoring issues raised on this repository. For more information on this change, please see the repository [README]( https://github.com/fortify/helm3-charts#readme) file.
