### ISSUE TITLE
Updated Chart for SSC AppVesrion: 23.2.1.0010?

### ISSUE THREAD

**Issue by emveee** [fortify/helm3-charts#27]
Fortify ScanCentral SAST Controller 23.2.1.0010 has been available for over a few months now but there seems to not be an update to the helm chart available to accompany it. When will this be released?

**Comment by brandon-langley-mf** [comment]
Hi, thanks for raising this issue, and sorry for the delay in getting back to you. We’ve been transitioning the Fortify Helm charts to Docker Hub, and the older Helm charts that used to be hosted in this repository have now been deprecated. If you think this issue is still relevant for the new Helm charts hosted on Docker Hub, please raise a support ticket through the regular OpenText support channels. We will no longer be monitoring issues raised on this repository. For more information on this change, please see the repository [README]( https://github.com/fortify/helm3-charts#readme) file.
