### ISSUE TITLE
Configurable Readiness Probe URL and Port in Helm Chart

### ISSUE THREAD

**Issue by tartru-std** [fortify/helm3-charts#29]
## Feature Request: Configurable Readiness Probe URL and Port in Helm Chart

**Description:**

We would like to request a feature that allows the configuration of the URL and port for the HTTP readiness probe in the Helm chart. This enhancement is necessary because using the external URL for the readiness probe can lead to a catch-22 situation with certain ingress controllers. These controllers only validate the route if the readiness probe is valid, leading to a deadlock.

**Comment by brandon-langley-mf** [comment]
Hi, thanks for raising this issue, and sorry for the delay in getting back to you. We’ve been transitioning the Fortify Helm charts to Docker Hub, and the older Helm charts that used to be hosted in this repository have now been deprecated. If you think this issue is still relevant for the new Helm charts hosted on Docker Hub, please raise a support ticket through the regular OpenText support channels. We will no longer be monitoring issues raised on this repository. For more information on this change, please see the repository [README]( https://github.com/fortify/helm3-charts#readme) file.
