### ISSUE TITLE
Defineable Extra configurations (volumes, volumeMounts, initContainers)

### ISSUE THREAD

**Issue by pipelineRat** [fortify/helm3-charts#30]
### Enhancement Request

It would be helpful if the Chart contained values to define extra volumes, volumeMounts, and initContainers so that resources like keystores and trusted certs can all be handled in code, and not manually created.

If users could declare InitContainers, they could utilize those to:
- Generate the Http Certificate Keystore
- Generate the JVM Truststore
- Add private network trusted certificates to the Truststore
- Secrets can be mounted as readOnly into an initContainer to generate the ssc.autoconfig file.

Extra Volumes and VolumeMounts would allow users to mount resources created in the initContainers into the primary webApp container

**Comment by brandon-langley-mf** [comment]
Hi, thanks for raising this issue, and sorry for the delay in getting back to you. We’ve been transitioning the Fortify Helm charts to Docker Hub, and the older Helm charts that used to be hosted in this repository have now been deprecated. If you think this issue is still relevant for the new Helm charts hosted on Docker Hub, please raise a support ticket through the regular OpenText support channels. We will no longer be monitoring issues raised on this repository. For more information on this change, please see the repository [README]( https://github.com/fortify/helm3-charts#readme) file.
