### ISSUE TITLE
Error occurred while detecting SCA version

### ISSUE THREAD

**Issue by mmurtha** [fortify/helm3-charts#31]
### Current Behavior

Using SAST chart 23.2.0 with controller and sensor 23.2 (or any more recent version, as well) I receive this error when the worker/sensor tries to start:

 `launcher.log will be stored in "/fortify/.fortify/scancentral-23.2.0/log" directory.
Checking for updates...
No update available or auto update is disabled on the controller.
scancentral.log will be stored in "/fortify/.fortify/scancentral-23.2.0/log" directory.
Setting up SCA version...
Retrieving SCA version...
Error occurred while detecting SCA version
Shutting down with errors. Please see log for details.`

This environment variable is present: 
`COM_FORTIFY_VERSION_SCA=23.2.0
`

The controller is up and running, and accessible to the worker.  It is also connected to SSC.

### Expected Behavior

Sensor to start up without error

### Steps To Reproduce

In a kubernetes environment, deploy scancentral-sast 23.2.0 chart with fortifydocker/scancentral-sast-controller:23.2 and fortifydocker/scancentral-sast-sensor:23.2

**Comment by brandon-langley-mf** [comment]
Hi, thanks for raising this issue, and sorry for the delay in getting back to you. We’ve been transitioning the Fortify Helm charts to Docker Hub, and the older Helm charts that used to be hosted in this repository have now been deprecated. If you think this issue is still relevant for the new Helm charts hosted on Docker Hub, please raise a support ticket through the regular OpenText support channels. We will no longer be monitoring issues raised on this repository. For more information on this change, please see the repository [README]( https://github.com/fortify/helm3-charts#readme) file.
