### ISSUE TITLE
Scancentral SAST not enabled by default on 24.2 - EKS/Helm

### ISSUE THREAD

**Issue by ruivit** [fortify/helm3-charts#32]
### Current Behavior

When deploying version 24.2 of SSC and SC with Helm, Scancentral SAST is not enabled by default even when specified on the values file.

Scancentral SAST was enabled by default on version 23.1.

This is an issue since the documentation says that restart of server is required to apply the configuration, and on a deployment in Kubernetes this is not possible.

### Expected Behavior

Scancentral SAST should be enabled by default and no restart should be needed.

### Steps To Reproduce

1. Install SSC and SC via helm
helm install fortify-sc -n fortify fortify/scancentral-sast --values=values.yml
helm install ssc -n fortify fortify/fortify-ssc --values=values.yml

2. When going to the settings page, scancentral is not enabled by default
![image](https://github.com/user-attachments/assets/0dd7ba53-9c2b-4d5c-b5d4-18d86b4cd529)

### Environment

```markdown
All Fortify components are on version 24.2
Helm - v3.15.3
Kubernetes - 1.29
```

### Anything else?

It appears that documentation was updated on the last commit but the values files remained the same. I wonder if something changed between version which are not being documented.

**Comment by Timpartage1** [comment]
hello team, could you please help on this?

**Comment by ruivitit** [comment]
Hello.

I confirm that this is also occurring on version 24.4.

When will the documentation be updated?

Thanks

**Comment by brandon-langley-mf** [comment]
Hi, thanks for raising this issue, and sorry for the delay in getting back to you. We’ve been transitioning the Fortify Helm charts to Docker Hub, and the older Helm charts that used to be hosted in this repository have now been deprecated. If you think this issue is still relevant for the new Helm charts hosted on Docker Hub, please raise a support ticket through the regular OpenText support channels. We will no longer be monitoring issues raised on this repository. For more information on this change, please see the repository [README]( https://github.com/fortify/helm3-charts#readme) file.
