### ISSUE TITLE
SSC 23.2 - pod is in CrashLoopBackOff status because of this permission issue :  mktemp: failed to create file via template ‘/app/etc/passwd.XXXXXXXXX’: Permission denied

### ISSUE THREAD

**Issue by justBeroe** [fortify/helm3-charts#33]
### Current Behavior

After performing helm upgrade to SSC 23.2 with user: uid: 1111 gid:1 [0 not permitted in our organization], the following error appears: ---> mktemp: failed to create file via template ‘/app/etc/passwd.XXXXXXXXX’: Permission denied

drwxrwx--- 2 root root 4096 Aug 30 07:45 etc

It looks like users do not have any read, write or execute on this folder /app/etc

### Expected Behavior

mktemp: failed to create file via template ‘/app/etc/passwd.XXXXXXXXX’: Permission denied should not appear when doing SSC helm upgrade with user: uid: 1111 gid: 1 [gid cannot be 0 in our policy [is not allowed]]

Please provide a way to fix in chart or image. Do we have Dockerfile to modify it? Thank you.

### Steps To Reproduce

bash-5.1$ pwd
/app
bash-5.1$ ls -la
drwxrwx--- 2 root root 4096 Aug 30 07:45 etc
bash-5.1$ chown :1 etc/
chown: changing group of 'etc/': Operation not permitted
bash-5.1$ chmod g+rwx etc/
chmod: changing permissions of 'etc/': Operation not permitted
bash-5.1$ whoami
fortify

### Environment

```markdown
SSC 23.2.0.0154

bash-5.1$ cat version.properties
previous =
installed = 23.2.0.0154
```

**Comment by brandon-langley-mf** [comment]
Hi, thanks for raising this issue, and sorry for the delay in getting back to you. We’ve been transitioning the Fortify Helm charts to Docker Hub, and the older Helm charts that used to be hosted in this repository have now been deprecated. If you think this issue is still relevant for the new Helm charts hosted on Docker Hub, please raise a support ticket through the regular OpenText support channels. We will no longer be monitoring issues raised on this repository. For more information on this change, please see the repository [README]( https://github.com/fortify/helm3-charts#readme) file.
