### ISSUE TITLE
LIM 24.2 - wrong key name used in the documentation. 

### ISSUE THREAD

**Issue by evan-cap** [fortify/helm3-charts#34]
### Current Behavior

Using the supplied command : 
```
kubectl create secret generic lim-jwt-security-key \
--type=Opaque \
--from-literal=key=$(openssl rand -base64 64)
```
Leads to this error : `Error: couldn't find key token in Secret fortify-scdast/lim-jwt-security-key`
### Expected Behavior

Using this command fixed the issue : 
```
kubectl create secret generic lim-jwt-security-key \
--type=Opaque \
--from-literal=token=$(openssl rand -base64 64)
```

### Steps To Reproduce

Run the commands above when deploying lim

### Environment

```markdown
ArgoCD : 2.12.3
Kubernetes : 1.29.3
```

**Comment by brandon-langley-mf** [comment]
Hi, thanks for raising this issue, and sorry for the delay in getting back to you. We’ve been transitioning the Fortify Helm charts to Docker Hub, and the older Helm charts that used to be hosted in this repository have now been deprecated. If you think this issue is still relevant for the new Helm charts hosted on Docker Hub, please raise a support ticket through the regular OpenText support channels. We will no longer be monitoring issues raised on this repository. For more information on this change, please see the repository [README]( https://github.com/fortify/helm3-charts#readme) file.
